// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTcpConnections():Promise<string>;

export function TerminateProcess(arg1:number):Promise<void>;
